name: NPM Publish

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version to use
        type: string
        default: '22'

permissions:
  packages: write
  contents: read

jobs:
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://npm.pkg.github.com

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
